### ISSUE TITLE
Failing to install under node.js ver 12.14.1

### ISSUE THREAD

**Issue by MF-85** [NubeIO/node-red-contrib-nube-logic#2]
i try to install this node but get the following error log.

OS: Raspbian GNU/Linux 10 (buster)
node -v = 12.14.1
npm -v = 6.13.4

`2020-01-15T20:33:31.784Z installieren : node-red-contrib-nube-logic 1.0.4

2020-01-15T20:33:31.894Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-nube-logic@1.0.4
2020-01-15T20:33:41.300Z [out] 
2020-01-15T20:33:41.300Z [out] > time@0.11.4 install /home/pi/.node-red/node_modules/time
2020-01-15T20:33:41.300Z [out] > node-gyp rebuild
2020-01-15T20:33:41.300Z [out] 
2020-01-15T20:33:43.613Z [out] make: Verzeichnis „/home/pi/.node-red/node_modules/time/build“ wird betreten
2020-01-15T20:33:43.618Z [out]   CXX(target) Release/obj.target/time/src/time.o
2020-01-15T20:33:46.593Z [err] In file included from ../src/time.cc:5:
2020-01-15T20:33:46.593Z [err] ../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
2020-01-15T20:33:46.593Z [err] ../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
2020-01-15T20:33:46.593Z [err]      , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
2020-01-15T20:33:46.593Z [err]                                                               ^
2020-01-15T20:33:46.675Z [err] ../src/time.cc: At global scope:
2020-01-15T20:33:46.675Z [err] ../src/time.cc:12:20: error: ‘Handle’ has not been declared
2020-01-15T20:33:46.675Z [err]    static void Init(Handle<Object> target) {
2020-01-15T20:33:46.675Z [err]                     ^~~~~~
2020-01-15T20:33:46.675Z [err] ../src/time.cc:12:26: error: expected ‘,’ or ‘...’ before ‘<’ token
2020-01-15T20:33:46.675Z [err]    static void Init(Handle<Object> target) {
2020-01-15T20:33:46.675Z [err]                           ^
2020-01-15T20:33:46.675Z [err] ../src/time.cc: In static member function ‘static void Time::Init(int)’:
2020-01-15T20:33:46.675Z [err] ../src/time.cc:16:20: error: ‘target’ was not declared in this scope
2020-01-15T20:33:46.675Z [err]      Nan::SetMethod(target, "time", Time_);
2020-01-15T20:33:46.675Z [err]                     ^~~~~~
2020-01-15T20:33:46.687Z [err] ../src/time.cc:16:20: note: suggested alternative: ‘tzset’
2020-01-15T20:33:46.687Z [err]      Nan::SetMethod(target, "time", Time_);
2020-01-15T20:33:46.687Z [err]                     ^~~~~~
2020-01-15T20:33:46.687Z [err]                     tzset
2020-01-15T20:33:46.703Z [err] ../src/time.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Time::Localtime(Nan::NAN_METHOD_ARGS_TYPE)’:
2020-01-15T20:33:46.703Z [err] ../src/time.cc:65:64: error: no matching function for call to ‘v8::Value::IntegerValue()’
2020-01-15T20:33:46.703Z [err]      time_t rawtime = static_cast<time_t>(info[0]->IntegerValue());
2020-01-15T20:33:46.703Z [err]                                                                 ^
2020-01-15T20:33:46.704Z [err] In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
2020-01-15T20:33:46.704Z [err]                  from ../../nan/nan.h:54,
2020-01-15T20:33:46.704Z [err]                  from ../src/time.cc:5:
2020-01-15T20:33:46.704Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2609:40: note: candidate: ‘v8::Maybe<long long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const’
2020-01-15T20:33:46.704Z [err]    V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
2020-01-15T20:33:46.704Z [err]                                         ^~~~~~~~~~~~
2020-01-15T20:33:46.704Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2609:40: note:   candidate expects 1 argument, 0 provided
2020-01-15T20:33:46.727Z [err] ../src/time.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Time::Mktime(Nan::NAN_METHOD_ARGS_TYPE)’:
2020-01-15T20:33:46.727Z [err] ../src/time.cc:119:103: error: no matching function for call to ‘v8::Value::Int32Value()’
2020-01-15T20:33:46.727Z [err]      tmstr.tm_sec   = Nan::Get(arg, Nan::New("seconds").ToLocalChecked()).ToLocalChecked()->Int32Value();
2020-01-15T20:33:46.727Z [err]                                                                                                        ^
2020-01-15T20:33:46.727Z [err] In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
2020-01-15T20:33:46.727Z [err]                  from ../../nan/nan.h:54,
2020-01-15T20:33:46.727Z [err]                  from ../src/time.cc:5:
2020-01-15T20:33:46.727Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
2020-01-15T20:33:46.727Z [err]    V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
2020-01-15T20:33:46.727Z [err]                                         ^~~~~~~~~~
2020-01-15T20:33:46.727Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
2020-01-15T20:33:46.727Z [err] ../src/time.cc:120:103: error: no matching function for call to ‘v8::Value::Int32Value()’
2020-01-15T20:33:46.727Z [err]      tmstr.tm_min   = Nan::Get(arg, Nan::New("minutes").ToLocalChecked()).ToLocalChecked()->Int32Value();
2020-01-15T20:33:46.727Z [err]                                                                                                        ^
2020-01-15T20:33:46.727Z [err] In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
2020-01-15T20:33:46.727Z [err]                  from ../../nan/nan.h:54,
2020-01-15T20:33:46.727Z [err]                  from ../src/time.cc:5:
2020-01-15T20:33:46.727Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
2020-01-15T20:33:46.727Z [err]    V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
2020-01-15T20:33:46.727Z [err]                                         ^~~~~~~~~~
2020-01-15T20:33:46.727Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
2020-01-15T20:33:46.728Z [err] ../src/time.cc:121:101: error: no matching function for call to ‘v8::Value::Int32Value()’
2020-01-15T20:33:46.728Z [err]      tmstr.tm_hour  = Nan::Get(arg, Nan::New("hours").ToLocalChecked()).ToLocalChecked()->Int32Value();
2020-01-15T20:33:46.728Z [err]                                                                                                      ^
2020-01-15T20:33:46.728Z [err] In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
2020-01-15T20:33:46.728Z [err]                  from ../../nan/nan.h:54,
2020-01-15T20:33:46.728Z [err]                  from ../src/time.cc:5:
2020-01-15T20:33:46.728Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
2020-01-15T20:33:46.728Z [err]    V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
2020-01-15T20:33:46.728Z [err]                                         ^~~~~~~~~~
2020-01-15T20:33:46.728Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
2020-01-15T20:33:46.734Z [err] ../src/time.cc:122:106: error: no matching function for call to ‘v8::Value::Int32Value()’
2020-01-15T20:33:46.734Z [err]      tmstr.tm_mday  = Nan::Get(arg, Nan::New("dayOfMonth").ToLocalChecked()).ToLocalChecked()->Int32Value();
2020-01-15T20:33:46.734Z [err]                                                                                                           ^
2020-01-15T20:33:46.734Z [err] In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
2020-01-15T20:33:46.734Z [err]                  from ../../nan/nan.h:54,
2020-01-15T20:33:46.734Z [err]                  from ../src/time.cc:5:
2020-01-15T20:33:46.734Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
2020-01-15T20:33:46.734Z [err]    V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
2020-01-15T20:33:46.734Z [err]                                         ^~~~~~~~~~
2020-01-15T20:33:46.734Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
2020-01-15T20:33:46.734Z [err] ../src/time.cc:123:101: error: no matching function for call to ‘v8::Value::Int32Value()’
2020-01-15T20:33:46.734Z [err]      tmstr.tm_mon   = Nan::Get(arg, Nan::New("month").ToLocalChecked()).ToLocalChecked()->Int32Value();
2020-01-15T20:33:46.734Z [err]                                                                                                      ^
2020-01-15T20:33:46.734Z [err] In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
2020-01-15T20:33:46.734Z [err]                  from ../../nan/nan.h:54,
2020-01-15T20:33:46.734Z [err]                  from ../src/time.cc:5:
2020-01-15T20:33:46.734Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
2020-01-15T20:33:46.734Z [err]    V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
2020-01-15T20:33:46.734Z [err]                                         ^~~~~~~~~~
2020-01-15T20:33:46.734Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
2020-01-15T20:33:46.734Z [err] ../src/time.cc:124:100: error: no matching function for call to ‘v8::Value::Int32Value()’
2020-01-15T20:33:46.734Z [err]      tmstr.tm_year  = Nan::Get(arg, Nan::New("year").ToLocalChecked()).ToLocalChecked()->Int32Value();
2020-01-15T20:33:46.734Z [err]                                                                                                     ^
2020-01-15T20:33:46.734Z [err] In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
2020-01-15T20:33:46.734Z [err]                  from ../../nan/nan.h:54,
2020-01-15T20:33:46.734Z [err]                  from ../src/time.cc:5:
2020-01-15T20:33:46.734Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
2020-01-15T20:33:46.734Z [err]    V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
2020-01-15T20:33:46.734Z [err]                                         ^~~~~~~~~~
2020-01-15T20:33:46.734Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
2020-01-15T20:33:46.734Z [err] ../src/time.cc:125:113: error: no matching function for call to ‘v8::Value::Int32Value()’
2020-01-15T20:33:46.734Z [err]      tmstr.tm_isdst = Nan::Get(arg, Nan::New("isDaylightSavings").ToLocalChecked()).ToLocalChecked()->Int32Value();
2020-01-15T20:33:46.734Z [err]                                                                                                                  ^
2020-01-15T20:33:46.734Z [err] In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
2020-01-15T20:33:46.734Z [err]                  from ../../nan/nan.h:54,
2020-01-15T20:33:46.734Z [err]                  from ../src/time.cc:5:
2020-01-15T20:33:46.734Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
2020-01-15T20:33:46.734Z [err]    V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
2020-01-15T20:33:46.734Z [err]                                         ^~~~~~~~~~
2020-01-15T20:33:46.734Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
2020-01-15T20:33:46.734Z [err] ../src/time.cc: At global scope:
2020-01-15T20:33:46.734Z [err] ../src/time.cc:134:21: error: variable or field ‘init’ declared void
2020-01-15T20:33:46.734Z [err]    static void init (Handle<Object> target) {
2020-01-15T20:33:46.734Z [err]                      ^~~~~~
2020-01-15T20:33:46.734Z [err] ../src/time.cc:134:21: error: ‘Handle’ was not declared in this scope
2020-01-15T20:33:46.736Z [err] ../src/time.cc:134:21: note: suggested alternative: ‘rand_r’
2020-01-15T20:33:46.736Z [err]    static void init (Handle<Object> target) {
2020-01-15T20:33:46.736Z [err]                      ^~~~~~
2020-01-15T20:33:46.736Z [err]                      rand_r
2020-01-15T20:33:46.737Z [err] ../src/time.cc:134:34: error: expected primary-expression before ‘>’ token
2020-01-15T20:33:46.737Z [err]    static void init (Handle<Object> target) {
2020-01-15T20:33:46.737Z [err]                                   ^
2020-01-15T20:33:46.737Z [err] ../src/time.cc:134:36: error: ‘target’ was not declared in this scope
2020-01-15T20:33:46.737Z [err]    static void init (Handle<Object> target) {
2020-01-15T20:33:46.737Z [err]                                     ^~~~~~
2020-01-15T20:33:46.742Z [err] ../src/time.cc:134:36: note: suggested alternative: ‘tzset’
2020-01-15T20:33:46.742Z [err]    static void init (Handle<Object> target) {
2020-01-15T20:33:46.742Z [err]                                     ^~~~~~
2020-01-15T20:33:46.742Z [err]                                     tzset
2020-01-15T20:33:46.743Z [err] In file included from ../../nan/nan.h:54,
2020-01-15T20:33:46.743Z [err]                  from ../src/time.cc:5:
2020-01-15T20:33:46.743Z [err] ../src/time.cc:137:21: error: ‘init’ was not declared in this scope
2020-01-15T20:33:46.743Z [err]    NODE_MODULE(time, init)
2020-01-15T20:33:46.743Z [err]                      ^~~~
2020-01-15T20:33:46.743Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:560:36: note: in definition of macro ‘NODE_MODULE_X’
2020-01-15T20:33:46.743Z [err]        (node::addon_register_func) (regfunc),                          \
2020-01-15T20:33:46.743Z [err]                                     ^~~~~~~
2020-01-15T20:33:46.743Z [err] ../src/time.cc:137:3: note: in expansion of macro ‘NODE_MODULE’
2020-01-15T20:33:46.743Z [err]    NODE_MODULE(time, init)
2020-01-15T20:33:46.743Z [err]    ^~~~~~~~~~~
2020-01-15T20:33:46.746Z [err] ../src/time.cc:137:21: note: suggested alternative: ‘int’
2020-01-15T20:33:46.746Z [err]    NODE_MODULE(time, init)
2020-01-15T20:33:46.746Z [err]                      ^~~~
2020-01-15T20:33:46.746Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:560:36: note: in definition of macro ‘NODE_MODULE_X’
2020-01-15T20:33:46.746Z [err]        (node::addon_register_func) (regfunc),                          \
2020-01-15T20:33:46.746Z [err]                                     ^~~~~~~
2020-01-15T20:33:46.746Z [err] ../src/time.cc:137:3: note: in expansion of macro ‘NODE_MODULE’
2020-01-15T20:33:46.746Z [err]    NODE_MODULE(time, init)
2020-01-15T20:33:46.746Z [err]    ^~~~~~~~~~~
2020-01-15T20:33:46.859Z [err] In file included from /home/pi/.cache/node-gyp/12.14.1/include/node/node.h:63,
2020-01-15T20:33:46.859Z [err]                  from ../../nan/nan.h:54,
2020-01-15T20:33:46.859Z [err]                  from ../src/time.cc:5:
2020-01-15T20:33:46.859Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
2020-01-15T20:33:46.859Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/node_object_wrap.h:84:78:   required from here
2020-01-15T20:33:46.859Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
2020-01-15T20:33:46.859Z [err]                 reinterpret_cast<Callback>(callback), type);
2020-01-15T20:33:46.859Z [err]                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-01-15T20:33:46.912Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
2020-01-15T20:33:46.912Z [err] ../../nan/nan_object_wrap.h:65:61:   required from here
2020-01-15T20:33:46.912Z [err] /home/pi/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
2020-01-15T20:33:47.135Z [err] make: *** [time.target.mk:109: Release/obj.target/time/src/time.o] Fehler 1
2020-01-15T20:33:47.135Z [out] make: Verzeichnis „/home/pi/.node-red/node_modules/time/build“ wird verlassen
2020-01-15T20:33:47.139Z [err] gyp
2020-01-15T20:33:47.140Z [err]  ERR!
2020-01-15T20:33:47.141Z [err]  build error 
2020-01-15T20:33:47.146Z [err] gyp
2020-01-15T20:33:47.146Z [err]  ERR! stack Error: `make` failed with exit code: 2
2020-01-15T20:33:47.146Z [err] gyp 
2020-01-15T20:33:47.146Z [err] ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
2020-01-15T20:33:47.146Z [err] gyp
2020-01-15T20:33:47.146Z [err]  ERR! stack     at ChildProcess.emit (events.js:223:5)
2020-01-15T20:33:47.146Z [err] gyp 
2020-01-15T20:33:47.147Z [err] ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
2020-01-15T20:33:47.147Z [err] gyp 
2020-01-15T20:33:47.148Z [err] ERR! System Linux 4.19.75-v7l+
2020-01-15T20:33:47.148Z [err] gyp
2020-01-15T20:33:47.148Z [err]  ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-01-15T20:33:47.148Z [err] gyp
2020-01-15T20:33:47.148Z [err]  ERR! cwd /home/pi/.node-red/node_modules/time
2020-01-15T20:33:47.148Z [err] gyp ERR! 
2020-01-15T20:33:47.148Z [err] node -v v12.14.1
2020-01-15T20:33:47.148Z [err] gyp
2020-01-15T20:33:47.148Z [err]  ERR! node-gyp -v v5.0.5
2020-01-15T20:33:47.149Z [err] gyp ERR! 
2020-01-15T20:33:47.149Z [err] not ok 
2020-01-15T20:33:47.674Z [err] npm
2020-01-15T20:33:47.674Z [err]  ERR! code ELIFECYCLE
2020-01-15T20:33:47.674Z [err] npm ERR! errno
2020-01-15T20:33:47.675Z [err]  1
2020-01-15T20:33:47.677Z [err] npm 
2020-01-15T20:33:47.677Z [err] ERR! time@0.11.4 install: `node-gyp rebuild`
2020-01-15T20:33:47.677Z [err] npm ERR! Exit status 1
2020-01-15T20:33:47.677Z [err] npm ERR! 
2020-01-15T20:33:47.677Z [err] npm ERR! Failed at the time@0.11.4 install script.
2020-01-15T20:33:47.677Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-01-15T20:33:47.697Z [err] 
2020-01-15T20:33:47.697Z [err] npm ERR! A complete log of this run can be found in:
2020-01-15T20:33:47.697Z [err] npm
2020-01-15T20:33:47.697Z [err]  ERR!     /home/pi/.npm/_logs/2020-01-15T20_33_47_682Z-debug.log
2020-01-15T20:33:47.713Z rc=1`

**Comment by AimeeQiu** [comment]
Hi Brother, how did you solve this problem？
